grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
model_selection:
  module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      criterion: gini
      min_samples_split: 2
      min_samples_leaf: 1
      n_jobs: -1
    search_param_grid:
      criterion:
        - entropy
        - log_loss
      min_samples_split:
        - 3
      min_samples_leaf:
        - 2
  module_1:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      criterion: gini
      min_samples_split: 2
      min_samples_leaf: 1
      n_jobs: -1
    search_param_grid:
      criterion:
        - entropy
        - log_loss
      min_samples_split:
        - 3
      min_samples_leaf:
        - 2
  module_2:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      loss: log_loss
      n_estimators: 50
      learning_rate: 1.0
      criterion: friedman_mse
    search_param_grid:
      loss:
        - deviance
      n_estimators:
        - 80
        - 100
      learning_rate:
        - 0.1
        - 0.01
      criterion:
        - squared_error

